/*
 * Trading API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "event_id")]
    pub event_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "bets_placed")]
    pub bets_placed: i64,
}

impl Event {
    pub fn new(event_id: uuid::Uuid, name: String, bets_placed: i64) -> Event {
        Event {
            event_id,
            name,
            bets_placed,
        }
    }
}
